### ISSUE TITLE
Cannot read property match of null, when using @if to hide stuff.

### ISSUE THREAD

**Issue by randohinn** [calebporzio/livewire#158]
**Describe the bug**

When using Blade's if statements to hide parts of a Livewire component, when toggling the condition, an 
```
Uncaught TypeError: Cannot read property 'match' of null
    at _default.parseOutMethodAndParams (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at _default.get (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at livewire.js?id=a6c7698e3078c78b0ef4:1
    at e.value (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at HTMLDivElement.a (livewire.js?id=a6c7698e3078c78b0ef4:1)
parseOutMethodAndParams @ livewire.js?id=a6c7698e3078c78b0ef4:1
get @ livewire.js?id=a6c7698e3078c78b0ef4:1
(anonymous) @ livewire.js?id=a6c7698e3078c78b0ef4:1
value @ livewire.js?id=a6c7698e3078c78b0ef4:1
a @ livewire.js?id=a6c7698e3078c78b0ef4:1
```

appears.

**To Reproduce**
Have a component:

```
<div>
	@if(count($contents) > 0 && !$open)
		<div class="border-black border border-gray-900 rounded-full min-w-8 w-auto px-4 h-8 inline-flex items-center justify-center absolute right-0 top-0 m-4 hover:bg-gray-700 hover:text-white cursor-pointer" wire:click="toggle">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="w-4 mr-2 fill-current"><path class="heroicon-ui" d="M17 16a3 3 0 1 1-2.83 2H9.83a3 3 0 1 1-5.62-.1A3 3 0 0 1 5 12V4H3a1 1 0 1 1 0-2h3a1 1 0 0 1 1 1v1h14a1 1 0 0 1 .9 1.45l-4 8a1 1 0 0 1-.9.55H5a1 1 0 0 0 0 2h12zM7 12h9.38l3-6H7v6zm0 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/></svg>
			{{ count($contents) }} {{ count($contents) > 1 ? "toodet" : "toode" }}
		</div>	
	@elseif($open)
		<div class="absolute right-0 top-0 m-4 p-8 bg-white rounded shadow w-1/2 lg:w-1/4">
			<div class="flex justify-between items-center pb-4 mb-4">
				<span class="uppercase font-semibold tracking-wide text-md">Ostukorv</span>
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="fill-current cursor-pointer hover:text-red-500" wire:click="toggle"><path class="heroicon-ui" d="M4.93 19.07A10 10 0 1 1 19.07 4.93 10 10 0 0 1 4.93 19.07zm1.41-1.41A8 8 0 1 0 17.66 6.34 8 8 0 0 0 6.34 17.66zM13.41 12l1.42 1.41a1 1 0 1 1-1.42 1.42L12 13.4l-1.41 1.42a1 1 0 1 1-1.42-1.42L10.6 12l-1.42-1.41a1 1 0 1 1 1.42-1.42L12 10.6l1.41-1.42a1 1 0 1 1 1.42 1.42L13.4 12z"/></svg>
			</div>
			@foreach($contents as $content)
				<div class="flex items-center justify-between py-4 border-b">
					<span class="uppercase text-sm tracking-wide font-medium text-gray-700">{{$content["name"]}}</span>
					<div>
						<span>{{ $content['count'] }}</span>
					</div>
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="text-gray-500 fill-current cursor-pointer hover:text-red-500"><path class="heroicon-ui" d="M16.24 14.83a1 1 0 0 1-1.41 1.41L12 13.41l-2.83 2.83a1 1 0 0 1-1.41-1.41L10.59 12 7.76 9.17a1 1 0 0 1 1.41-1.41L12 10.59l2.83-2.83a1 1 0 0 1 1.41 1.41L13.41 12l2.83 2.83z"/></svg>

				</div>
			@endforeach
		</div>
	@endif

</div>
```

```
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ShoppingCart extends Component
{
	public $contents = [["name" => "Paar pükse", "cost" => 100, "count" => 1], ["name" => "Paar pükse", "cost" => 100, "count" => 1], ["name" => "Paar pükse", "cost" => 100, "count" => 1], ["name" => "Paar pükse", "cost" => 100, "count" => 1]];
	public $open = false;

	public function toggle() {
		$this->open = !$this->open;
	}

    public function render()
    {
        return view('livewire.shopping-cart');
    }
}
```
Click on the count, then the X and see the console error out.

**Expected behavior**
No console error

**Desktop (please complete the following information):**
 - Chromium Version 76.0.3809.87 (Official Build) Built on Ubuntu , running on LinuxMint 19 (64-bit)

**Comment by bdweix** [comment]
I've also been encountering similar errors. I do not have a way to replicate yet and am working on nailing down the bug. I am getting the occasional error: 
```
livewire.js?id=d46ffb7faa09f88464bf:1 Uncaught (in promise) TypeError: Cannot read property 'getAttributeNames' of null
    at e.value (livewire.js?id=d46ffb7faa09f88464bf:1)
    at new e (livewire.js?id=d46ffb7faa09f88464bf:1)
    at new DOMElement (livewire.js?id=d46ffb7faa09f88464bf:1)
    at DOMElement.value (livewire.js?id=d46ffb7faa09f88464bf:1)
    at DOMElement.value (livewire.js?id=d46ffb7faa09f88464bf:1)
    at onNodeAdded (livewire.js?id=d46ffb7faa09f88464bf:1)
    at M (livewire.js?id=d46ffb7faa09f88464bf:1)
    at k (livewire.js?id=d46ffb7faa09f88464bf:1)
    at k (livewire.js?id=d46ffb7faa09f88464bf:1)
    at k (livewire.js?id=d46ffb7faa09f88464bf:1)
```

Currently this error will stop the Livewire components from working on the page. I wonder if it's possible to catch these errors and throw an exception on the backend.

**Comment by randohinn** [comment]
> I've also been encountering similar errors. I do not have a way to replicate yet and am working on nailing down the bug. I am getting the following:
> 
> ```
> livewire.js?id=d46ffb7faa09f88464bf:1 Uncaught (in promise) TypeError: Cannot read property 'getAttributeNames' of null
>     at e.value (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at new e (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at new DOMElement (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at DOMElement.value (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at DOMElement.value (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at onNodeAdded (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at M (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at k (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at k (livewire.js?id=d46ffb7faa09f88464bf:1)
>     at k (livewire.js?id=d46ffb7faa09f88464bf:1)
> ```
> 
> Currently this error will stop the Livewire components from working on the page. I wonder if it's possible to catch these errors and throw an exception on the backend.

You're hitting a bigger wall then, in my case, the component still works.

**Comment by 2kodes** [comment]
@bdweix 

hello..
Are you by any chance retrieving or setting values for an input or select like this : 
` <input type="number" class="form-control"  value="{!! old('no_of_trainees',$training->no_of_trainees)  !!}"  wire:model="no_of_trainees" />`

i had a similar situation with the same error as yours. Took me a while to figure it out and remove the `old()` and it worked

**Comment by mauricius** [comment]
```
livewire.js?id=a6c7698e3078c78b0ef4:1 Uncaught (in promise) TypeError: Cannot read property 'getAttributeNames' of null
    at e.value (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at new e (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at new DOMElement (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at DOMElement.value (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at DOMElement.value (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at onNodeAdded (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at N (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at g (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at g (livewire.js?id=a6c7698e3078c78b0ef4:1)
    at g (livewire.js?id=a6c7698e3078c78b0ef4:1)
```
I have the same error of @bdweix. Looks like that this is popping up when in the Blade component there is an `if` statement.

@calebporzio is it possible to use an unminified version of the JS file? Right now source maps are not helping either.

**Comment by calebporzio** [comment]
Ok, I figured it out. That was a tough one.

You are wrapping a <div> in a conditional. Livewire thinks it is the same element after the else statement is reached, so the parent still has the `wire:click` event listener attached, but no `wire:click` attribute.

The fix for this is to add `wire:key="something"` to each of the root divs in the conditinoal.

**Comment by intrepidws** [comment]
@calebporzio Looks like something got dropped from your answer here, would you mind updating? I'm running into a similar issue here and hoping this might be my fix too.

**Comment by calebporzio** [comment]
This should fix the issue:
```
<div>
	@if(count($contents) > 0 && !$open)
		<div wire:key="foo" class="border-black border border-gray-900 rounded-full min-w-8 w-auto px-4 h-8 inline-flex items-center justify-center absolute right-0 top-0 m-4 hover:bg-gray-700 hover:text-white cursor-pointer" wire:click="toggle">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="w-4 mr-2 fill-current"><path class="heroicon-ui" d="M17 16a3 3 0 1 1-2.83 2H9.83a3 3 0 1 1-5.62-.1A3 3 0 0 1 5 12V4H3a1 1 0 1 1 0-2h3a1 1 0 0 1 1 1v1h14a1 1 0 0 1 .9 1.45l-4 8a1 1 0 0 1-.9.55H5a1 1 0 0 0 0 2h12zM7 12h9.38l3-6H7v6zm0 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/></svg>
			{{ count($contents) }} {{ count($contents) > 1 ? "toodet" : "toode" }}
		</div>	
	@elseif($open)
		<div wire:key="bar" class="absolute right-0 top-0 m-4 p-8 bg-white rounded shadow w-1/2 lg:w-1/4">
			<div class="flex justify-between items-center pb-4 mb-4">
				<span class="uppercase font-semibold tracking-wide text-md">Ostukorv</span>
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="fill-current cursor-pointer hover:text-red-500" wire:click="toggle"><path class="heroicon-ui" d="M4.93 19.07A10 10 0 1 1 19.07 4.93 10 10 0 0 1 4.93 19.07zm1.41-1.41A8 8 0 1 0 17.66 6.34 8 8 0 0 0 6.34 17.66zM13.41 12l1.42 1.41a1 1 0 1 1-1.42 1.42L12 13.4l-1.41 1.42a1 1 0 1 1-1.42-1.42L10.6 12l-1.42-1.41a1 1 0 1 1 1.42-1.42L12 10.6l1.41-1.42a1 1 0 1 1 1.42 1.42L13.4 12z"/></svg>
			</div>
			@foreach($contents as $content)
				<div class="flex items-center justify-between py-4 border-b">
					<span class="uppercase text-sm tracking-wide font-medium text-gray-700">{{$content["name"]}}</span>
					<div>
						<span>{{ $content['count'] }}</span>
					</div>
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="text-gray-500 fill-current cursor-pointer hover:text-red-500"><path class="heroicon-ui" d="M16.24 14.83a1 1 0 0 1-1.41 1.41L12 13.41l-2.83 2.83a1 1 0 0 1-1.41-1.41L10.59 12 7.76 9.17a1 1 0 0 1 1.41-1.41L12 10.59l2.83-2.83a1 1 0 0 1 1.41 1.41L13.41 12l2.83 2.83z"/></svg>

				</div>
			@endforeach
		</div>
	@endif

</div>
```

**Comment by ya-cha** [comment]
Giving keys to that div didn't solve it for me. But it issue gave me the idea to wrap each condition into a div:

```
<div>
	<div>
		@if($condition)
			...
		@endif
	</div>
	<div>
		@if(!$condition)
			...
		@endif
	</div>
</div>
```

Disadvantage: You can't use @elseif or @else.
But I'm fine with that right now.
